db = new Mongo().getDB("recruit_tracker");

db.createCollection("users", { capped: false });

// db.users.insertMany([
//   { first_name: "HR", last_name: "Manager", email: "hr@cgi.com" },
//   { first_name: "Student", last_name: "Test", email: "student@cgi.com" },
// ]);

db.users.insertMany([
  {
    college: "UAB",
    email: "student01@example.com",
    feedback: { " ": " " },
    gradDate: "05/2026",
    linkedIn: "https://linkedin.com/in/student01",
    locationPreferences: "Birmingham, Atlanta, Chicago",
    name: "Student One",
    password: "$2b$12$randomHashValue01",
    position: "internship",
    preference: "internship",
    resume: null,
    resume_hash: "randomResumeHash01",
    stage: "Applied",
    state: "AL",
    _id: "student01@example.com",
  },
  {
    college: "Georgia Tech",
    email: "student02@example.com",
    feedback: { " ": " " },
    gradDate: "06/2027",
    linkedIn: "https://linkedin.com/in/student02",
    locationPreferences: "Atlanta, Savannah, Macon",
    name: "Student Two",
    password: "$2b$12$randomHashValue02",
    position: "full-time",
    preference: "full-time",
    resume: null,
    resume_hash: "randomResumeHash02",
    stage: "Interviewed",
    state: "GA",
    _id: "student02@example.com",
  },
  {
    college: "MIT",
    email: "student03@example.com",
    feedback: { " ": " " },
    gradDate: "04/2028",
    linkedIn: "https://linkedin.com/in/student03",
    locationPreferences: "Cambridge, Boston, Worcester",
    name: "Student Three",
    password: "$2b$12$randomHashValue03",
    position: "internship",
    preference: "internship",
    resume: null,
    resume_hash: "randomResumeHash03",
    stage: "Offered",
    state: "MA",
    _id: "student03@example.com",
  },
  // Entries 4 through 14 are omitted for brevity
  {
    college: "Caltech",
    email: "student15@example.com",
    feedback: { " ": " " },
    gradDate: "09/2029",
    linkedIn: "https://linkedin.com/in/student15",
    locationPreferences: "Pasadena, Los Angeles, Irvine",
    name: "Student Fifteen",
    password: "$2b$12$randomHashValue15",
    position: "research",
    preference: "research",
    resume: null,
    resume_hash: "randomResumeHash15",
    stage: "Applied",
    state: "CA",
    _id: "student15@example.com",
  },
]);
